server:
  port: 8080
#  servlet:
#    context-path: /blog
spring:
  datasource:
    username: root
    password: Chinasoft
    url: jdbc:mysql://127.0.0.1:3306/personal_blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 500
        min-idle: 0
        max-wait: -1
        max-active: 8
    lettuce:
      shutdown-timeout: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.whkj.project.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#minio
minio:
  bucket: home
  host: http://82.156.171.228:9001
  url: ${minio.host}/${minio.bucket}/
  accessKey: miniowlq
  secretKey: kaifa123456
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: JXU0RTJEJXU1NkZELSV1NTMxNyV1NEVBQy0ldTdBMEIldTVFOEYldTU0NTgtJXU0RTJBJXU0RUJBJXU1MzVBJXU1QkEyLXN1cGVyc3RhcmxpcXVu
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 14400000


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
#logback
logging:
  config:
   classpath: logback.xml
# 作为备注但是用不到
pic:
  resource: D:/resource/
